---
# TODO: 
#   - Use import_tasks only
#   - Standardize output

- hosts: localhost

  # tell ansible to not use ssh
  connection: local

  vars:
    git_config_user_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61636135343362353438343934656666316338373265326430646365636531383633316665353338
          3364613765643336373036386666373061396331653065340a386331343161383663303331326635
          33343364333636306438323066306566656633663135363130353561356136356531646139643534
          3161393939343035330a633130626262636366363863356534356235353137666565653764636465
          31366565623436363734383766353137656636636166376337656264643963623561
    git_config_user_name: "DevSallSa"
    git_config_core_editor: "vim"
    git_config_core_autocrlf: "input"
    git_config_init_default_branch: "main"
    git_config_pull_rebase: "false"
    git_config_alias_adog: "log --all --decorate --oneline  --graph"
    ssh_src_path: "./.ssh/"
    ssh_dest_path: "{{ lookup('env', 'HOME') }}/.ssh/"
  

  # Tasks to perform first
  # tasks to complete before running roles
  pre_tasks:
    
    # update cache for arch linux
    - name: pre-run | update package cache (arch)
      # use root profile to perform tasks
      become: true
      # In case of running specific tasks
      tags: 
        - install
        - core
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
    
    # update cache for Debian and derivatives....
    # For getting system info with ansible,
    # $ ansible localhost -m gather_facts
    - name: pre-run | update package cache (Debian, Pop, Ubuntu,...)
      become: true
      tags: 
        - install
        - core
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]

  tasks:
    - name: "include_tasks => ansible setup"
      include_tasks: tasks/ansible.yml
      tags: ansible

    - name: "import_tasks => git"
      import_tasks: tasks/ssh.yml

    - name: "include_tasks => core setup"
      include_tasks: tasks/core-setup.yml
      tags: core

    - name: "include_tasks => zsh"
      include_tasks: tasks/zsh-setup.yml
      tags: zsh

    - name: "include_tasks => prompt setup"
      include_tasks: tasks/prompt-setup.yml
      tags: prompt

    - name: "include_tasks => kitty terminal"
      include_tasks: tasks/kitty.yml
      tags: kitty

    - name: "import_tasks => git"
      import_tasks: tasks/git.yml

    - name: "include_tasks => dotfiles"
      include_tasks: tasks/dotfiles-setup.yml
      tags: dotfiles

    - name: "include_tasks => brave"
      include_tasks: tasks/brave.yml
      tags: 
        - install
        - brave

    - name: "include_tasks => desktop"
      include_tasks: tasks/desktop-setup.yml
      tags: desktop
...          
