---
- hosts: localhost
  # In case of running specific tasks
  tags: always

  # tell ansible to not use ssh
  connection: local
  
  # use root profile to perform tasks
  become: true

  # Tasks to perform first
  # tasks to complete before running roles
  pre_tasks:
    
    # update cache for arch linux
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
    
    # update cache for Debian and derivatives....
    # For getting system info with ansible,
    # $ ansible localhost -m gather_facts
    - name: pre-run | update package cache (Debian, Pop, Ubuntu,...)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]

  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/desktop-setup.yml
    - include_tasks: tasks/dotfiles-setup.yml
...          
