---
- hosts: localhost
  # In case of running specific tasks
  tags: always

  # tell ansible to not use ssh
  connection: local
  
  # use root profile to perform tasks
  become: true

  # Tasks to perform first
  # tasks to complete before running roles
  pre_tasks:
    
    # update cache for arch linux
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
    
    # update cache for Debian and ubuntu....
    - name: pre-run | update package cache (Debian, ubuntu,...)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Ubuntu", "Debian"]

# all machine will have the "base" role and
# will execute the tasks related to this role
# - hosts: all
#   tags: base
#   become: true
#   roles:
#     - base

# if the machine belong to the "server" roles
# - hosts: server
#   tags: server
#   become: true
#   roles:
#     - server


  tasks:
    - name: Install htop
      package:
        name: 
          - python3-psutil
          - aptitude
          - htop
          - tmux
          - vim

    - name: Copy wallpaper file
      copy:
        src: files/pantherflat.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root

    # set wallpaper for gnome
    - name: Set wallpaper for gnome
      become_user: usagi
      dconf: 
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

    - name: Set wallpaper position
      become_user: usagi
      dconf: 
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
