---
- hosts: localhost

  # tell ansible to not use ssh
  connection: local

  vars:
    git_config_user_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61636135343362353438343934656666316338373265326430646365636531383633316665353338
          3364613765643336373036386666373061396331653065340a386331343161383663303331326635
          33343364333636306438323066306566656633663135363130353561356136356531646139643534
          3161393939343035330a633130626262636366363863356534356235353137666565653764636465
          31366565623436363734383766353137656636636166376337656264643963623561
    git_config_user_name: "DevSallSa"
    git_config_core_editor: "vim"
    git_config_core_autocrlf: "input"
    git_config_init_default_branch: "main"
    git_config_pull_rebase: "false"
    git_config_alias_adog: "log --all --decorate --oneline  --graph"
    ssh_src_path: "./.ssh/"
    ssh_dest_path: "{{ ansible_env.HOME }}/.ssh/"
    ansible_tmp_path: "/tmp/ansible"


  # Tasks to perform first
  # tasks to complete before running roles
  pre_tasks:

    # update cache for arch linux
    - name: pre-run | update package cache (arch)
      # use root profile to perform tasks
      become: true
      # In case of running specific tasks
      tags:
        - install
        - core
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    # update cache for Debian and derivatives....
    # For getting system info with ansible,
    # $ ansible localhost -m gather_facts
    - name: pre-run | update package cache (Debian, Pop, Ubuntu,...)
      become: true
      tags:
        - install
        - core
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]

  tasks:
    - name: "include_tasks => ansible setup"
      include_tasks: tasks/ansible.yml
      tags: ansible

    - name: "include_tasks => core setup"
      import_tasks: tasks/core-setup.yml

    - name: "import_tasks => ssh"
      import_tasks: tasks/ssh.yml

    - name: "include_tasks => zsh"
      import_tasks: tasks/zsh-setup.yml

    - name: "include_tasks => prompt setup"
      include_tasks: tasks/prompt-setup.yml
      tags: prompt

    - name: "include_tasks => kitty terminal"
      include_tasks: tasks/kitty.yml
      tags: kitty

    - name: "import_tasks => fonts"
      import_tasks: tasks/fonts-setup.yml
      vars:
        fonts_path: "{{ ansible_env.HOME }}/.local/share/fonts"

    - name: "import_tasks => git"
      import_tasks: tasks/git.yml

    - name: "import_tasks => neovim"
      import_tasks: tasks/neovim.yml
      vars:
        neovim_file: "{{ ansible_env.HOME }}/Apps/nvim.appimage"

    - name: "import_tasks => nodejs"
      import_tasks: tasks/nodejs.yml

    - name: "import_tasks => node packages"
      import_tasks: tasks/nodejs-packages.yml

    - name: "import_tasks => sdkman!"
      import_tasks: tasks/sdkman.yml

    - name: "include_tasks => brave"
      include_tasks: tasks/brave.yml
      tags:
        - install
        - brave

    - name: "import_tasks => productivity"
      import_tasks: tasks/productivity.yml

    - name: "import_tasks => utilities"
      import_tasks: tasks/utils.yml

    - name: "import_tasks => entertainment"
      import_tasks: tasks/entertainment.yml

    - name: "include_tasks => dotfiles"
      import_tasks: tasks/dotfiles-setup.yml

    - name: "include_tasks => desktop"
      import_tasks: tasks/desktop-setup.yml

    - name: "import_tasks => docker"
      import_tasks: tasks/docker-setup.yml

    # TODO:
    #   - Prompt installation finish
    #   - Ask user to reboot system
...
