#!/usr/bin/env bash

###################################################################
# Description  : Run script for ansible execution
# Author       : DevSallSa
# Email        : devsallsa@linuxmail.org
# Date         : 2022-12-24
# Version      : 1.1.0
###################################################################

sudo apt-get update -y
sudo apt install -y software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible

export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share

ansible-playbook "$@" ./local.yml
