---
- name: Install ansible requirements
  become: true
  apt:
    name: 
      - python3-psutil
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags:
    - ansible

- name: Install Ansible Galaxy
  shell: ansible-galaxy collection install -r requirements.yml --upgrade
  tags:
    - ansible

- name: Create ansible temp directory
  file:
    dest: "{{ ansible_tmp_path }}"
    state: directory
  tags: ansible
...
