---
- name: Install ansible requirements
  become: true
  apt:
    name:
      - python3-psutil
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: ansible

- name: (ansible) Install Ansible Galaxy
  shell: ansible-galaxy collection install -r requirements.yml --upgrade
  tags: ansible
...
