---
- name: Install core packages
  become: yes
  apt:
    name: 
      - aptitude
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - lsb_release
      - python3-pip
      - tree
      - wget
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: &core ["install", "core"]

- name: Install productivity packages
  become: yes
  apt:
    name: 
      - bat
      - gcc
      - git
      - htop
      - jq
      - make
      - neofetch
      - ripgrep
      - shellcheck
      - sqlite3
      - ssh
      - stow
      - tmux
      - valgrind
      - vim
      - xclip
      - zip
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: *core
...
