---
- name: Install core packages
  become: true
  apt:
    name: 
      - aptitude
      - batcat
      - ca-certificates
      - curl
      - gnupg
      - htop
      - lsb_release
      - python3-pip
      - tmux
      - vim
      - xclip
      - wget
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags:
    - install
    - core
...
