---
- name: Install core packages
  become: yes
  apt:
    name:
      - aptitude
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - libnotify-bin
      - lsb-release
      - python3-pip
      - ssh
      - tree
      - wget
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: &core ["install", "core"]

- name: Install productivity packages
  become: yes
  apt:
    name:
      - bat
      - ffmpeg
      - gcc
      - git
      - htop
      - jq
      - make
      - neofetch
      - python3-venv
      - ripgrep
      - shellcheck
      - sqlite3
      - ssh
      - stow
      - tmux
      - valgrind
      - vim
      - xclip
      - zip
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: cores

- name: Setting up new bin folders
  become: yes
  shell: mkdir -p /opt/bin
  tags: *core
