---
- name: Install core packages
  become: true
  apt:
    name: 
      - python3-pip
      - aptitude
      - batcat
      - curl
      - htop
      - tmux
      - vim
      - wget
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags:
    - install
    - core
...
