---
- name: Install core packages
  become: true
  apt:
    name:
      - aptitude
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - libnotify-bin
      - lsb-release
      - ssh
      - tree
      - wget
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: &core ['install', "core"]

- name: Upgrade packages
  become: true
  apt:
    autoremove: yes
    upgrade: yes
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: *core

- name: Install productivity packages
  become: true
  apt:
    name:
      - bat
      - ffmpeg
      - gcc
      - git
      - htop
      - jq
      - make
      - neofetch
      - pandoc
      - python3-pip
      - python3-venv
      - ripgrep
      - shellcheck
      - sqlite3
      - ssh
      - stow
      - tmux
      - valgrind
      - vim
      - xclip
      - zip
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: *core

- name: Setting up new bin folders
  become: true
  shell: mkdir -p /opt/bin
  tags: *core
...
