---
- name: Install Gnome tweaks tool
  become: true
  apt:
    name: gnome-tweaks
  tags: &desktop ["desktop"]
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Copy wallpaper files
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/
    owner: root
    group: root
  tags: *desktop
  with_fileglob:
    - files/backgrounds/*

# set wallpaper for Gnome on Pop_OS!
# Use dconf-cli for dumping dconf value
# or just check dconf-editor
- name: Set wallpaper for Pop-COSMIC
  become: true
  become_user: "{{ ansible_env.USER }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/light-paper.jpg'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Set wallpaper for Pop-COSMIC dark mode
  become: true
  become_user: "{{ ansible_env.USER }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/dark-paper.jpg'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Set wallpaper position
  become: true
  become_user: "{{ ansible_env.USER }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Set Kitty terminal as default
  become: true
  community.general.alternatives:
    name: x-terminal-emulator
    link: /usr/bin/x-terminal-emulator
    path: "{{ ansible_env.HOME }}/.local/bin/kitty"
    state: selected
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

    ###########################
    # Gnome custom keybinding #
    ###########################

- name: Set brave browser shortcut name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Launch brave browser'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Set command for brave browser shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'brave-browser-stable'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Bind key for brave browser
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Super><Shift>b'"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'

- name: Enable custom keybindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  tags: *desktop
  when: ansible_env.DESKTOP_SESSION == 'pop'
...
