---
- name: Copy wallpaper files
  copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/
    owner: root
    group: root
  with_fileglob:
    - files/backgrounds/*
  tags: &desktop ['desktop']

# set wallpaper for Gnome on Pop_OS!
# Use dconf-cli for dumping dconf value
# or just chech dconf-editor
- name: Set wallpaper for Pop-COSMIC
  become_user: "{{ lookup('env', 'USER') }}"  
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ironflat.jpg'"
  tags: *desktop
  when: "lookup('env', 'DESKTOP_SESSION') is eq 'pop'"

- name: Set wallpaper for Pop-COSMIC dark mode
  become_user: "{{ lookup('env', 'USER') }}"  
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/pantherflat.jpg'"
  tags: *desktop
  when: "lookup('env', 'DESKTOP_SESSION') is eq 'pop'"

- name: Set wallpaper position
  become_user: "{{ lookup('env', 'USER') }}"  
  dconf: 
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
  tags: *desktop
  when: "lookup('env', 'DESKTOP_SESSION') is eq 'pop'"
...
