---
- name: Download dotfiles
  ansible.builtin.git:
    repo: git@github.com:DevSallSa/.dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
  tags: dotfiles

- name: Installing dotfiles
  args:
    executable: /usr/bin/bash
  shell: "{{ ansible_env.HOME }}/.dotfiles/install.sh"
  tags: dotfiles
...
