---
# TODO: install dotfiles
# - delete config folder to be stowed
- name: Set bash config
  copy:
    src: files/bashrc
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  tags: dotfiles
...
