---
- name: Check if nerdfonts are already installed
  stat:
    path: "{{ fonts_path }}/NerdFonts/"
  register: nerdfonts
  tags: &font ["install", "fonts"]

# Microsoft fonts are proprietary
# we can't use them for commercial use
- name: Install microsoft proprietary fonts
  become: true
  apt:
    name: ttf-mscorefonts-installer
  tags: *font

- name: Download JetBrains, VictorMono nerd-fonts
  shell: |
    curl -fsSL https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0-RC/VictorMono.zip \
                -o "{{ ansible_tmp_path }}/VictorMono.zip"
    curl -fsSL https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0-RC/JetBrainsMono.zip \
                -o "{{ ansible_tmp_path }}/JetBrainsMono.zip"
  tags: *font
  when: nerdfonts.stat.isdir is not defined

- name: Install JetBrains, VictorMono nerd-fonts
  shell: |
    mkdir -p "{{ fonts_path }}/NerdFonts"
    unzip -uo "{{ ansible_tmp_path }}/VictorMono.zip" \
                -d "{{ fonts_path }}/NerdFonts/VictorMono"
    unzip -uo "{{ ansible_tmp_path }}/JetBrainsMono.zip" \
                -d "{{ fonts_path }}/NerdFonts/JetBrainsMono"
    fc-cache -fv "{{ fonts_path }}"
  tags: *font
  when: nerdfonts.stat.isdir is not defined
...
