---
- name: (npm) Install Yarn
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g yarn
  tags: &npm ["install", "nodejs", "npm"]

- name: (npm) Install PNPM
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g pnpm
    pnpm setup
  tags: *npm

- name: (pnpm) Install Typescript
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    pnpm install -g typescript
  tags: *npm

- name: (pnpm) Install Create-React-App
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    pnpm install -g create-react-app
  tags: *npm

- name: (pnpm) Install Angular CLI
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    pnpm install -g @angular/cli
  tags: *npm
...
