- name: (npm) Install Yarn
  become: yes
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g yarn
  tags: &npm [ "install", "nodejs", "npm"]

- name: (npm) Install Typescript
  become: yes
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g typescript
  tags: *npm

- name: (npm) Install Create-React-App
  become: yes
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g create-react-app
  tags: *npm

- name: (npm) Install Angular CLI
  become: yes
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm use node;
    npm install -g @angular/cli
  tags: *npm
