- name: (npm) Install Yarn
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  command: /usr/bin/zsh -c "source $HOME/.zshrc; 
    nvm use node;
    npm install -g yarn"
  tags: &npm [ "install", "nodejs", "npm"]

- name: (npm) Install typescript
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  command: /usr/bin/zsh -c "source $HOME/.zshrc; 
    nvm use node;
    npm install -g typescript"
  tags: *npm

- name: (npm) Install Create-React-App
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  command: /usr/bin/zsh -c "source $HOME/.zshrc; 
    nvm use node;
    npm install -g create-react-app"
  tags: *npm

- name: (npm) Install Angular CLI
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  command: /usr/bin/zsh -c "source $HOME/.zshrc; 
    nvm use node;
    npm install -g @angular/cli"
  tags: *npm

