---
- name: Check if Node.js is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.config/nvm"
  register: node
  tags: &nodejs ["install", "nodejs"]

- name: Get Node Version Manager (nvm)
  ansible.builtin.git:
    repo: 'https://github.com/nvm-sh/nvm.git'
    dest: "{{ ansible_env.HOME }}/.config/nvm"
    force: true
  tags: *nodejs
  when: node.stat.isdir is not defined

- name: Install Node Version Manager (nvm)
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    cd "{{ ansible_env.XDG_CONFIG_HOME }}/nvm" && \
    git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" \
                          $(git rev-list --tags --max-count=1)` && \
    chmod +x ./nvm.sh && ./nvm.sh
  tags: *nodejs
  when: node.stat.isdir is not defined

- name: Load nvm in Z-shell
  shell: |
    echo "\n" >> "{{ ansible_env.HOME }}/.zshrc"
    echo "# NVM DEFAULT SOURCING" >> "{{ ansible_env.HOME }}/.zshrc"
    echo 'export NVM_DIR="$XDG_CONFIG_HOME/nvm"' >> "{{ ansible_env.HOME }}/.zshrc"
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> \
                                "{{ ansible_env.HOME }}/.zshrc"

    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> \
                                "{{ ansible_env.HOME }}/.zshrc"
  tags: *nodejs
  when: node.stat.isdir is not defined

- name: Install latest Node.js LTS
  become: true
  become_user: "{{ ansible_env.USER }}"
  args:
    executable: /usr/bin/zsh
  shell: |
    source "{{ ansible_env.HOME }}/.zshrc"
    nvm install --lts
  tags: *nodejs
  when: node.stat.isdir is not defined
...
