---
- name: Install peek for screen recording
  become: true
  apt:
    name: peek
  when: ansible_distribution in ["Pop!_OS", "Ubuntu", "Debian"]
  tags: &prod ["install", "productivity"]

- name: Install gnome-pomodoro
  become: true
  apt:
    name: gnome-shell-pomodoro
  when: ansible_env.DESKTOP_SESSION == 'pop'
  tags: *prod

- name: Remove old gnome-calendar
  become: true
  apt:
    name: gnome-calendar
    state: absent
  when: ansible_env.DESKTOP_SESSION == 'pop'
  tags: *prod

- name: (Flatpak) Install Cheese
  community.general.flatpak:
    name: org.gnome.Cheese
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Gnome Calendar
  community.general.flatpak:
    name: org.gnome.Calendar
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Planner
  community.general.flatpak:
    name: com.github.alainm23.planner
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Remmina
  community.general.flatpak:
    name: org.remmina.Remmina
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install WPS
  community.general.flatpak:
    name: com.wps.Office
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Zoom
  community.general.flatpak:
    name: us.zoom.Zoom
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Typora
  community.general.flatpak:
    name: io.typora.Typora
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Gnome sticky note
  community.general.flatpak:
    name: org.gnome.Notes
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install OBS Studio
  community.general.flatpak:
    name: com.obsproject.Studio
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Flameshot
  community.general.flatpak:
    name: org.flameshot.Flameshot
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Gimp
  community.general.flatpak:
    name: org.gimp.GIMP
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Inkscape
  community.general.flatpak:
    name: org.inkscape.Inkscape
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Audacity
  community.general.flatpak:
    name: org.audacityteam.Audacity
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Rhythmbox
  community.general.flatpak:
    name: org.gnome.Rhythmbox3
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Nextcloud
  community.general.flatpak:
    name: com.nextcloud.desktopclient.nextcloud
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Bitwarden
  community.general.flatpak:
    name: com.bitwarden.desktop
    state: present
    method: user
  tags:
    - *prod
    - flatpak

- name: (Flatpak) Install Spotify
  community.general.flatpak:
    name: com.spotify.Client
    state: present
    method: user
  tags:
    - *prod
    - flatpak
...
