---
- name: Check if starship is already installed
  stat:
    path: "{{ ansible_tmp_path }}/install-starship.sh"
  register: starship
  tags: &starship ["install", "starship"]

- name: Install Starship prompt
  become: true
  shell: |
    curl -sS https://starship.rs/install.sh -o "{{ ansible_tmp_path }}/install-starship.sh"
    chmod +x "{{ ansible_tmp_path }}/install-starship.sh"
    "{{ ansible_tmp_path }}/install-starship.sh" -y
  tags: *starship
  when: not starship.stat.exists

- name: Setup Starship starship
  shell: |
    echo 'eval "$(starship init zsh)"' >> \
               "{{ ansible_env.HOME }}/.zshrc"
  tags: *starship
  when: not starship.stat.exists
...
