---
- name: Create .ssh directory
  file:
    dest: "{{ ssh_dest_path }}"
    mode: 0700
    state: directory
  tags: &ssh ["ssh"]

- name: Install ssh keys
  copy:
    src: "{{ ssh_src_path }}"
    dest: "{{ ssh_dest_path }}"
    mode: 0600
  tags: *ssh

- name: To create ssh keys, execute the command in /tmp/ansible/new-ssh.log
  shell: |
    echo 'ssh-keygen -a 100 -t ed25519 -C "<your-identifier>"' > \
                "{{ ansible_tmp_path }}/new-ssh.log"
  tags: new-ssh
...
